name: GitHub Actions Demo
on: [push]
jobs:
  Ckeck-python-version:
    runs-on: ubuntu-latest
    steps:
      - run: python --version
  Testing-code-with-pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - run: pylint app.py
